### ISSUE TITLE
Prepare the Patatrack branch for merging into CMSSW

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#200]
Track here any issues related to merging the Patatrack branch with the upstream CMSSW master branch.

**Comment by fwyzard** [comment]
- [ ] merge #172
  - [ ] merge #157
  - [ ] merge #170 and restore lost changes to RiemannFit.h after the migration to 10.4.x
  - [ ] review and merge #189 
  - [ ] review and merge #197 (supersedes #192, closes #191)
  - [ ] merge #199 (includes #193 and #198)
  - [ ] what about #100 and #119 ?
  - [ ] review #160 and decide if it should be used
  - [ ] revert forcing use of HLT conditions ? see [RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py](https://github.com/cms-sw/cmssw/compare/master...cms-patatrack:CMSSW_10_4_X_Patatrack#diff-4e4e386df550fa27f52ff680d9d0f183)

Do we need to include these files ?
  - [ ] 27kB / 1.8k lines: EventFilter/SiPixelRawToDigi/test/RawId_moduleId.txt
  - [ ] 3.7MB / 53k lines: EventFilter/SiPixelRawToDigi/test/Pixel_Phase1_Raw2Digi_GPU_Cabling_Map.dat

**Comment by fwyzard** [comment]
Remove obsolete files under Remove obsolete EventFilter/SiPixelRawToDigi/test/ with #201 .

**Comment by fwyzard** [comment]
RFC PR for master: https://github.com/cms-sw/cmssw/pull/25353 .

**Comment by makortel** [comment]
> - [ ] what about #100 and #119 ?

I'd like to see #100 included and all modules migrated to it before merging to CMSSW master (after completing the steps in https://github.com/cms-patatrack/cmssw/pull/100#issuecomment-440701647). We can of course revisit this after all other steps have been finished if my plan takes long to execute.

**Comment by makortel** [comment]
@fwyzard I noticed  cms-sw#25353  uses CMSSW_10_4_X_Patatrack as the source branch. Do we want the CMSSW PR to get updated every time we merge anything in the patatrack repository?

**Comment by fwyzard** [comment]
> Do we want the CMSSW PR to get updated every time we merge anything in the patatrack repository?

For the moment I'd say we do.
Once we fix the conflicts, get some feedback, and the checklist above stabilises a bit, we can branch off something for integration.

**Comment by fwyzard** [comment]
I think by now all issues have either been addressed, or dropped.
Further changes can be done during the upstream review process, or after the merge.
