### ISSUE TITLE
factorise and review the code changes used for CTD19

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#309]
We need to factorise into independent PRs, review and eventually merge (part of) the developments used for Connecting The Dots 2019 (see #291 and/or the [`CMSSW_10_5_X_Patatrack_CTD19`](https://github.com/cms-patatrack/cmssw/tree/CMSSW_10_5_X_Patatrack_CTD19) branch).

History of PRs that are summed up there:
  - [ ] #265 Broken line fit
  - [ ] #266 Speed Up Pixel Track fitting
  - [ ] #269 Pixel Ntuple Fitters on cpu
  - [ ] #270 Add ability to save inner pixel triplets as well (if satisfy a condition)
  - [ ] #271 make CUDA code compiling (and running) on CPU
  - [x] #276 Pixel cluster size cut on gpu
  - [ ] #295 Fix bugs in Riemann and BrokenLine fits
  - [ ] #296 tune cuts to better reproduce 2018 HLT
  - [ ] #297 make "vertex by density" default
  - [ ] #304 Triplet Cleaner by hits
  - [ ] #311 Clean Digis and Hits
  - [ ] #312 Make use of Cache allocator in "CA"
  - [x] #322 implement RecHit SOA and move to new framework
  - [ ] #324 CTD19 developments for review and merging
  - [x] #329 CTD19 developments for review and merging (fixed)

**Comment by fwyzard** [comment]
Doing a proper review of over 100 modified files after the fact is, as expected, simply not possible.
