### ISSUE TITLE
Remove the use of CUDA API wrappers

### ISSUE THREAD

**Issue by makortel** [cms-patatrack/cmssw#386]
This issue is to track progress for removing the use of CUDA API wrappers. The library turned out to not be that useful (see some discussion in https://github.com/cms-patatrack/cmssw/issues/279#issuecomment-473053760)).

We are currently using the following components (extracted with `git grep`, may be incomplete)

- [x] `cuda::device_t::create_stream()` done partly in #389, completed in #404
- [x] `cuda::stream_t<>` done partly in #389, completed in #404 (except for `HeterogeneousEDProducer`)
- [x] `cuda::stream::wrap()` done in #389
- [x] `cuda::stream_t<>::enqueue::callback()` done in #389 (except for `HeterogeneousEDProducer`)
- [x] `cuda::event_t` done partly in #389, completed in #404
- [x] `cuda::event::create()` done partly in #389, completed in #404
- [x] `cuda::memory::copy()` done in #395
- [x] `cuda::memory::async::copy()` done in #395
- [x] `cuda::memory::device::zero()` done in #395
- [x] `cuda::memory::device::async::set()` done in #395
- [x] `cuda::memory::device::make_unique()` done in #396
- [x] `cuda::memory::host::make_unique()` done in #396
- [x] `cuda::device::count()` done in #408
- [x] `cuda::device::get()` done in #408
- [x] `cuda::device::set()` done in #408
- [x] `cuda::device::current::get()` done in #408
- [x] `cuda::device::current::scoped_override_t<>` done in #407
- [x] `cuda::launch()` done in #390
- [x] `cuda::throw_if_error()` done in #414
- [x] `cuda::is_success()` done in #389

**Comment by makortel** [comment]
@fwyzard About the `cuda::throw_if_error()`, given that we are mostly using `cudaCheck()`, how about changing `cudaCheck()` such that there would be a compile-time flag whether to `abort()` or throw an exception? (such that in CMSSW `master` it would throw an exception, patatrack and private forks could still use the `abort()`)

**Comment by makortel** [comment]
I'll start with removing the streams and events.

**Comment by fwyzard** [comment]
OK.
I'll have a look at providing an equivalent of `cuda::launch()`.

**Comment by fwyzard** [comment]
`cuda::launch()` does not support functions objects or lambdas - just plain functions, right ?

**Comment by makortel** [comment]
> `cuda::launch()` does not support functions objects or lambdas - just plain functions, right ?

I believe it is just a wrapper for the kernel launch `<<<...>>>`, so the passed function has to be `__global__` function (or whatever CUDA kernel launch supports).

**Comment by makortel** [comment]
First part of streams and events is done in #389.

**Comment by fwyzard** [comment]
@makortel I have prepared an alternative for `cuda::launch()`.

Do you prefer to keep the same syntax, e.g.
```c++
launch(kernel, {gridDim, blockDim, sharedMem = 0, stream = nullptr}, args...);
```
or something more like what Cupla uses, e.g.
```c++
launch(kernel)(gridDim, blockDim, sharedMem = 0, stream = nullptr)(args...);
```
?

**Comment by makortel** [comment]
@fwyzard I don't have a clear preference (I would have probably gone with the bare kernel launch syntax, i.e. `<<<...>>>`, but am really fine with ~any syntax since the use is not that widespread).

**Comment by fwyzard** [comment]
OK, I'll stick to the current syntax then, since it is simpler to implement.

The advantage over the `kernel<<<...>>>(...)` syntax is that `launch(kernel, {...},  ...)` can be used also in the host compiler.

**Comment by fwyzard** [comment]
I have asked @waredjeb to look into the `cuda::memory` operations, replacing
  - [ ] `cuda::memory::device::make_unique()` with `cudautils::make_device_unique()`
  - [ ] `cuda::memory[::async]::copy()` with `cudaMemcpy[Async]()`
  - [ ] `cuda::memory[::async]::zero()` and `::set()` with `cudaMemset[Async]()`

**Comment by makortel** [comment]
> * `cuda::memory::device::make_unique()` with `cudautils::make_device_unique()`

The `cudautils::make_device_unique()` is not a direct replacement as it (currently) requires the CUDA stream (although I'm thinking to add a variant that caches the allocation but is not "tied" to a CUDA stream).

IIRC all calls to `cuda::memory::device::make_unique()` are in unit tests. I was thinking that maybe the API wrappers could be acceptable there. On the other hand, using the `CUDAStreamCache` to get the stream for the allocator is not too hard either.

**Comment by fwyzard** [comment]
Would it work to explicitly pass stream 0 (actually `nullptr`) to use the default stream ?

**Comment by makortel** [comment]
> Would it work to explicitly pass stream 0 (actually `nullptr`) to use the default stream ?

Probably, since all `*Async` API calls accept that (right?).

**Comment by fwyzard** [comment]
I think they do.

**Comment by fwyzard** [comment]
> @fwyzard About the `cuda::throw_if_error()`, given that we are mostly using `cudaCheck()`, how about changing `cudaCheck()` such that there would be a compile-time flag whether to `abort()` or throw an exception? (such that in CMSSW `master` it would throw an exception, patatrack and private forks could still use the `abort()`)

Sorry @makortel looks like I never answered you: given that an uncaught exception results anyway in an `abort()` can we just make the replacement for good ?

**Comment by makortel** [comment]
@fwyzard 

> given that an uncaught exception results anyway in an `abort()` can we just make the replacement for good ?

I didn't follow if you meant "`cudaCheck()` should throw exception" or "`cudaCheck()` should abort"?

(also, exceptions from places where we call CUDA APIs should get caught by the framework)

**Comment by fwyzard** [comment]
I meant, `cudaCheck()` should just throw exceptions.

> exceptions from places where we call CUDA APIs should get caught by the framework

Right... but they would still result in a stack trace and in the job ending, shouldn't they ?

**Comment by makortel** [comment]
#404 completes the work for streams and events.

**Comment by makortel** [comment]
I can take care of `cuda::device::current::scoped_override_t<>` after #404 gets merged.

**Comment by waredjeb** [comment]
I can work on the remaining ```cuda::device```calls!

**Comment by fwyzard** [comment]
The last references to the CUDA API Wrappers were removed via #417 .
